name: Build and Push Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Convert org/repo to lowercase
      - name: Prepare variables
        id: vars
        run: |
          ORG_LOWER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(basename "${GITHUB_REPOSITORY}")
          SHA_SHORT=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "org=${ORG_LOWER}" >> $GITHUB_OUTPUT
          echo "repo=${REPO_NAME}" >> $GITHUB_OUTPUT
          echo "sha_short=${SHA_SHORT}" >> $GITHUB_OUTPUT

      # Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/${{ steps.vars.outputs.org }}/${{ steps.vars.outputs.repo }}:latest
            ghcr.io/${{ steps.vars.outputs.org }}/${{ steps.vars.outputs.repo }}:${{ steps.vars.outputs.sha_short }}
            ghcr.io/${{ steps.vars.outputs.org }}/${{ steps.vars.outputs.repo }}:${{ github.ref_name }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}

      - name: Show image info
        run: |
          echo "Image pushed:"
          echo "ghcr.io/${{ steps.vars.outputs.org }}/${{ steps.vars.outputs.repo }}:latest"
          echo "ghcr.io/${{ steps.vars.outputs.org }}/${{ steps.vars.outputs.repo }}:${{ steps.vars.outputs.sha_short }}"
          echo "ghcr.io/${{ steps.vars.outputs.org }}/${{ steps.vars.outputs.repo }}:${{ github.ref_name }}"
